### PR TITLE
Adding async methods to BraintreeService and TransactionGateway

### PR DESCRIPTION
**Pull request by ejohnsonTKTNET**
Added .NET 4.5.2-targeting Debug452 and Release452 configurations and
updated csproj files so target framework switches with configuration
(i.e. original .NET 2.0/3.5 targeting should remain intact with Debug
and Release configurations). 4.5.2 is the lowest framework version still
supported by Microsoft.

### CODE REVIEW

**Comment by ejohnsonTKTNET** [comment]
I noticed [this old pull request](https://github.com/braintree/braintree_dotnet/pull/5) re: async support. Hopefully you'll be able to leverage the way the configurations are set up here and NuGet's [multi-targeting](https://docs.nuget.org/create/enforced-package-conventions#matching-assembly-version-to-the-target-framework-of-a-project) to both support async for clients on newer versions of the .NET framework as well as continue to support version 2.0 for backwards compatibility.

**Comment by pblesi** [comment]
@ejohnsonTKTNET 

Thank you for submitting this pull request. We will review it and let you know if any further changes are required.

Thanks!

**Comment by ejohnsonTKTNET** [comment]
Any update on this?

**Comment by danakatz** [comment]
@ejohnsonTKTNET After some internal discussion, we’ve decided not to make this change. It's possible to implement concurrency at a higher level without adding asynchronous functionality to the library and increasing maintenance overhead.

Thanks again for the PR!

**Comment by ejohnsonTKTNET** [comment]
Concurrency is not the same as async. An ASP.NET application is already naturally concurrent. Async/await improves scalability and throughput--threads do not block while waiting for external processes, e.g. the response from your server, and are free to handle other requests.

I'd like to talk to you more about this. Not supporting async means that you are effectively artificially limiting the performance of your clients' applications.

**Comment by pblesi** [comment]
@ejohnsonTKTNET 

After some discussion, we have decided to support async in our library. No timeline yet on when this will be available, but we are working on it. 

Thanks!

**Comment by AlexKeySmith** [comment]
I agree with @ejohnsonTKTNET, async is available all the way back to .net 4.0 (with KB2468871 installed back in 2011) https://blogs.msdn.microsoft.com/bclteam/2012/10/22/using-asyncawait-without-net-framework-4-5/ it's a shame not to be using it.

**Comment by onlyann** [comment]
@pblesi 

It is good to know you are working on supporting an async API.
How is this progressing?

**Comment by bluk** [comment]
@onlyann We are still working on adding async support. We will try to raise the priority of finishing the work. Thanks for your patience.

**Comment by danakatz** [comment]
As of Braintree 3.6.0, released today, async methods are available for all API operations! Thanks for the work you did on this, @ejohnsonTKTNET - we credited you in the changelog.

Please let us know if you encounter any issues or things we can do to improve this feature.

**Pull request closed without merging**
