### PR TITLE
Addition of `ToLowerInvariant()` on the `environment` parameter in `Environment.ParseEnvironment()`

### PR DESCRIPTION
**Pull request by Psypher9**
# Summary
I only made direct changes to `Environment.cs` and `EnvironmentTest.cs`. The large number of additions is from me updated my fork to the latest version before making changes. Like I said in my latest commit's comment, I ran all of the tests and the integration tests were failing because they couldn't connect to the remote server, but the `EnvironmentTest` tests were all passing.

Do you guys make the addition to the changelog? I couldn't find anything about it.

# Checklist

- [ ] Added changelog entry
- [ x ] Ran unit tests (See README for instructions)

### CODE REVIEW

**Comment by jackellenberger** [comment]
@Psypher9 looks like there's a bunch of extra diff in here, would you mind just committing [src/Braintree/Environment.cs](https://github.com/braintree/braintree_dotnet/pull/74/files#diff-232fb07114829b2f2a1426448a5c10a6) and [test/Braintree.Tests/EnvironmentTest.cs](https://github.com/braintree/braintree_dotnet/pull/74/files#diff-905d683c606548105c0fda1171af6599)?

**Comment by Psypher9** [comment]
Certainly!

**Comment by jackellenberger** [comment]
@Psypher9 would you still like this change in? Do you need any help cleaning it up?

**Comment by Psypher9** [comment]
Yeah I would like to make this change. I am having difficulty keeping the other diffs out though. Most of those changes were in a commit on my fork that was from me getting my fork up to date with yours. I don't really know why they are showing as real changes.

**Comment by jackellenberger** [comment]
Gotcha. If you have the git CLI installed, my recommendation would be to reset back to master (`git reset HEAD~8`) which will remove your existing commits but leave the files untouched, so you'll still have your work done as a diff. Then you can add just the files we want with `git add src/Braintree/Environment.cs test/Braintree.Tests/EnvironmentTest.cs`. From that point you can either `git commit` and `git push -f` to clobber your existing commits with just the minimal change set, or you can create another branch and commit to that in case you want to preserve the original branch.

If you don't have the time, we can also make the changes on our end and attribute them to you in the changelog. Whatever works for you!

**Comment by Psypher9** [comment]
Okay great! I'll give that a try. Do I need to make a new PR?

**Comment by crookedneighbor** [comment]
Do whatever is easiest for you.

**Comment by Psypher9** [comment]
Okay. I'm going to close this one and make a new one.

**Pull request closed without merging**
