### PR TITLE
Cross target .NETCOREAPP3.1 to remove transient dependencies

### PR DESCRIPTION
**Pull request by iamcarbon**
# Summary

# Checklist

- [ ] Added changelog entry
- [x] Ran unit tests (See README for instructions)

This PR cross targets .NETCOREAPP3.1 and conditionally upgrades Newtonsoft.Json to avoid bringing in any additional dependencies or facades on modern runtimes.

### CODE REVIEW

**Comment by hollabaq86** [comment]
👋  @iamcarbon thanks for the PR. Can you elaborate on your reason for this PR? 

Introducing an additional target framework increases the complexity of managing our SDK, so I want to make sure we're being considerate of .NET folks who consume our SDK while managing our maintenance workload.

**Comment by iamcarbon** [comment]
Hi @hollabaq86. The System.Xml.XPath.XmlDocument dependency brings in 10+ direct dependencies and even more transient dependencies when run on .NETCOREAPP3.1+.

These libraries were temporary artifacts before the re-unification of .NET cumulating in the .NET 5.0 release and have not been updated since 2016. Eliminating these artifacts speeds up build times, reduces deployment sizes, and eliminates the chances of a future library conflict.

It also helps assure that the library is considering and testing the runtimes that the .NETSTANDARD libraries abstract. .NETCOREAPP3.1 is the latest LTS release for .NET and promoted as the best choice for developing any new .NET applications needing LTS.

**Comment by hollabaq86** [comment]
👋   @iamcarbon I spun up a Core 2.1 container with these changes to make sure we're not breaking compatibility with folks still on that version, and I'm seeing the following build errors:

```                                               
/usr/share/dotnet/sdk/2.1.814/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.TargetFrameworkInference.targets(137,5): error NETSDK1045: The current .NET SDK does not support targeting .NET Core 3.1.  Either target .NET Core 2.1 or lower, or use a version of the .NET SDK that supports .NET Core 3.1. [/home/admin/bt/braintree-dotnet/src/Braintree/Braintree.csproj]  
```

A quick way to reproduce this issue would be to pull the code from our old [dockerfile-core2](https://github.com/braintree/braintree_dotnet/blob/4.18.0/Dockerfile-core2) file, update for Core 2.1, and modify the [Makefile commands](https://github.com/braintree/braintree_dotnet/blob/34a5e8dae5a198be860d8762622a720f81b015bf/Makefile#L12) to build this container on your machine.

I'm a little stumped on potential workarounds for this issue... if we're unable to find a solution that doesn't break existing functionality for Core 2.1 users we'll need to pass on this PR until we can drop Core 2.1 support in Aug 2021.

**Comment by iamcarbon** [comment]
@hollabaq86 Bump now that that .NETCOREAPP2.1 is EOL.

**Comment by cgdibble** [comment]
Hey @iamcarbon, thanks for the bump! You are right in that 2.1 is EOL. We definitely have this work in the pipeline, but it will be coming with a broader set of work for the next major version of the SDK.

**Comment by smendoza88** [comment]
@cgdibble bump 3.1 EOL is Dec 3, 2022

**Pull request closed without merging**
